name: build-and-test-template
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
jobs:
  plan:
    runs-on: ubuntu-20.04 
    if: always()
    steps:
    - uses: actions/checkout@v3
      name: Checkout source code
    - uses: hashicorp/setup-terraform@v3
    - name: Install tfcmt
      uses: jaxxstorm/action-install-gh-release@v1.11.0
      with:
        repo: suzuki-shunsuke/tfcmt
        tag: v4.14.0
    - name: Create markdown for comment
      run: echo "# Plan for projects/${{inputs.target}}" > output.md
    - name: terraform init
      run: |
        terraform -chdir=stacks/projects/${{inputs.target}} init -no-color -input=false
    - name: Plan
      run: |
        terraform -chdir=stacks/projects/${{inputs.target}} plan -no-color -detailed-exitcode -out ${{ inputs.target }}.tfplan > ${{ inputs.target }}.log 2> stderr.log
    - name: tfcmt plan
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        REPO=$(echo ${{ github.repository }} | cut -f2 -d "/")
        tfcmt -owner ${{ github.repository_owner }} -repo $REPO -pr ${{ github.event.pull_request.number }} -var target:${{inputs.target}} plan -- cat ${{ inputs.target }}.log >> /dev/null
  apply:
    needs:
    - plan
    runs-on: ubuntu-20.04
    environment: ${{ inputs.target }}
    steps:
    - run: exit 1
